### PR TITLE
Load the symbols of BLIS when we use this package

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
@xrq-phys 
Is it ok to recompile `blis_jll` such that we have two shared libraries?
One LP64 and another one ILP64?

**Comment by xrq-phys** [comment]
Sure. BLIS' lib is not huge. It'd be nice to have two libs.

I'm not perfectly sure about library naming in case of 32+64bit `blis_jll`. Perhaps compile twice when `${nbits}==64` [here](https://github.com/JuliaPackaging/Yggdrasil/blob/master/B/blis/build_tarballs.jl)?

**Comment by amontoison** [comment]
I opened a PR to generate `blis32_jll`, but it's easier to maintain if we have the two shared libraries in the same `build_tarballs.jl`.
The names `libopenblas` and `libopenblas64_` are used for LP64 / ILP64 versions of openblas. We can do something similar.
We just need to be careful and change the soname of one shared library but I already did it here: https://github.com/JuliaPackaging/Yggdrasil/pull/6608

**Comment by amontoison** [comment]
We could also create a common script and keep two jll.
https://github.com/JuliaPackaging/Yggdrasil/tree/master/L/LAPACK

Update: It seems ok to use the name `libblis` for LP64 and ILP64 versions if they are in two jll.

**Comment by jd-foster** [comment]
Having an `__init__` that calls to `BLAS.lbt_forward` might be more appropriately added under the `BLIS.BLASInterface` module; a user of the other APIs might not expect this change.

**Comment by amontoison** [comment]
I opened this PR to have the same behavior with `MKL.jl` and `AppleAccelerate.jl` (https://github.com/JuliaMath/AppleAccelerate.jl/pull/58) but I don't want to break something for the users of BLIS.jl.

**Comment by xrq-phys** [comment]
BLIS.jl does much more than MKL.jl.

BLIS.jl directly overrides LinearAlgebra.jl functionalities. So like `rand(100) * rand(100)` operations will use BLIS once `using BLIS` was called *without going through libblastrampoline*.

The reason here is to support more generic storage of input matrices: If `view(mat, 1:2:end, 1:2:end)` goes through LinearAlgebra.jl's backend, either the whole submatrix is copied or BLAS is unused at all. This API-level overriding allows these kind of calls to go into BLIS' extended APIs.

In fact, I'm thinking of separating BLIS.jl into two packages: One provides access to the BLIS API and another one overwrites LinearAlgebra.jl functionalities.

**Comment by xrq-phys** [comment]
I just realized that the package aiming at (MKL.jl and AppleAccelerate.jl-like) BLAS-backend switching is already available as a separate one: BLISBLAS.jl

Then for BLIS.jl we'd better focus on overriding LinearAlgebra.jl via trait or reflection. @jd-foster I would like to have your opinion.

**Comment by amontoison** [comment]
For information, I'm just interested to load an LP64 BLIS.
I'm working on an Julia-HSL / HSL_jll.jl package with the HSL team and it requires an LP64 BLAS / LAPACK. Julia doesn't load an LP64 BLAS / LAPACK by default so we need to load one with `lbt_forward`.
Currently, the available options are OpenBLAS32_jll.jl or MKL_jll.jl. I would like to add an easy way to use BLIS32_jll.jl + LAPACK32_jll.jl.

For the new Apple Accelerate, we will need Julia 1.9 and the version 5.7.0 of LBT.

**Comment by amontoison** [comment]
I just checked BLISBLAS.jl and it's exactly what I need. I didn't know that this package was registered!

**Comment by jd-foster** [comment]
@amontoison BLISBLAS.jl is quite minimal: https://github.com/JuliaLinearAlgebra/BLISBLAS.jl/blob/main/src/BLISBLAS.jl. It just loads `blis_jll` and `LinearAlgebra` and then does your `__init__`.

Look like you found it while I was typing.

**Comment by amontoison** [comment]
Yep, let's close this PR.
I will open a PR to add blis32_jll in BLISBLAS.jl.

Thanks for the explanations!

**Comment by jd-foster** [comment]
> I will open a PR to add blis32_jll in BLISBLAS.jl.

I think this is the best course of action.

Note that as you found in https://github.com/JuliaLinearAlgebra/libblastrampoline/issues/117#issuecomment-1513772658
that (only) 157 symbols are loaded when using `BLAS.lbt_forward` with the `libblis` library at moment, so there is still some work to do:
cf. https://github.com/JuliaLinearAlgebra/libblastrampoline/issues/36

**Comment by jd-foster** [comment]
@xrq-phys You're right to define the scope of the BLIS package to be different from doing the LBT forwarding that is covered by BLISBLAS.jl. 

I wonder if there is still some functionality that could be added to make LBT forwarding work too. This should be on demand (i.e. not automatically on package loading) such as when some environment variable is set (e.g `BLIS_LBT_FOWARD` or similar).

**Comment by xrq-phys** [comment]
Created #21

**Pull request closed without merging**
