### PR TITLE
Replace `ENV["HOME"]` with `homedir()`

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
hat-tip @giordano

**Review by xrq-phys — APPROVED** [review]

**Comment by xrq-phys** [comment]
Wait.. Why Windows failed 😨

**Comment by giordano** [comment]
Might be something on julia nightly.  Can you reproduce the failure also on the `master` branch here?

**Comment by jd-foster** [comment]
I think the 'hat-tipped' [suggestion](https://discourse.julialang.org/t/are-there-any-plans-to-support-blis-in-julia/19620/14) was this instead?:
```
if isfile(joinpath(homedir(), ".blis_jlbla_blacklist"))
    blacklist = readdlm(joinpath(homedir(), ".blis_jlbla_blacklist"))
end
```

**Comment by xrq-phys** [comment]
Made my edit. Thanks.

**Comment by jd-foster** [comment]
Still failing on Windows with julia nightly...

**Comment by giordano** [comment]
> Can you reproduce the failure also on the master branch here?

☝️

**Comment by jd-foster** [comment]
Apparently so: https://github.com/JuliaLinearAlgebra/BLIS.jl/actions/runs/3354457163/jobs/5558019412

**Comment by xrq-phys** [comment]
No jl filename in this package appears in error trace. Hmm

**Comment by jd-foster** [comment]
I think this can be safely merged to `master`. The failure on windows julia nightly is a separate matter: see #23.

**Pull request merged**
